

services:
  # MongoDB database
  mongodb:
    image: mongo:6.0
    container_name: ecommerce-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: ecommerce_db
    networks:
      - ecommerce-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 5

  # Streamlit E-commerce App
  ecommerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-streamlit
    restart: unless-stopped
    ports:
      - "8501:8501"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - ecommerce-network
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local

networks:
  ecommerce-network:
    driver: bridge